### PR TITLE
User types example code

### PR DESCRIPTION
**Pull request by bmatsuo-at-luthersystems**
This is the code from the talk I gave, along with an example which I didn't have time to cover in the main talk.

### CODE REVIEW

**Comment by bmatsuo-at-luthersystems** [comment]
Ugh. Something happening on this branch. I meant to put this code under _examples.

**Comment by jeremy-asher** [comment]
Nice, thanks! Is there any significance to the `_solved` suffix on some of the filenames?

**Comment by bmatsuo-at-luthersystems** [comment]
Ah. Right. I guess I started that because address-book.lisp was representing the "problem" and the other files were the "solution" to the problem.

**Comment by jeremy-asher** [comment]
Ah, gotcha.

**Review by jeremy-asher — APPROVED** [review]

**Pull request merged**
